<?php

namespace SampleVendor\Interview;

interface RouterInterface
{
	/**
	 * Adds a path
	 *
	 * @param string   $path
	 * @param callable $callback
	 */
	public function add($path, callable $callback);

	/**
	 * Dispatches the request
	 *
	 * @param  string $request
	 * @return mixed  Returns the output generated by the matched path's callback
	 */
	public function dispatch($request);
}
